let comments = [
  {
    postId: 1,
    id: 1,
    name: "Elizabeth Clark",
    email: "elizabeth.clark@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 1,
    id: 2,
    name: "Charles Johnson",
    email: "charles.johnson@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 1,
    id: 3,
    name: "James Taylor",
    email: "james.taylor@example.com",
    body: "Good explanation, thanks.",
  },
  {
    postId: 1,
    id: 4,
    name: "Mary Smith",
    email: "mary.smith@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 1,
    id: 5,
    name: "Susan Clark",
    email: "susan.clark@example.com",
    body: "Wonderful post, thank you.",
  },
  {
    postId: 1,
    id: 6,
    name: "Joseph Martin",
    email: "joseph.martin@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 1,
    id: 7,
    name: "Joseph Robinson",
    email: "joseph.robinson@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 1,
    id: 8,
    name: "Charles Lewis",
    email: "charles.lewis@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 2,
    id: 9,
    name: "Susan Harris",
    email: "susan.harris@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 2,
    id: 10,
    name: "Sarah Martin",
    email: "sarah.martin@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 2,
    id: 11,
    name: "Karen Brown",
    email: "karen.brown@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 2,
    id: 12,
    name: "James Rodriguez",
    email: "james.rodriguez@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 2,
    id: 13,
    name: "Richard Rodriguez",
    email: "richard.rodriguez@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 2,
    id: 14,
    name: "Elizabeth Walker",
    email: "elizabeth.walker@example.com",
    body: "Great article!",
  },
  {
    postId: 2,
    id: 15,
    name: "Patricia Thomas",
    email: "patricia.thomas@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 2,
    id: 16,
    name: "Jessica Harris",
    email: "jessica.harris@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 2,
    id: 17,
    name: "David Harris",
    email: "david.harris@example.com",
    body: "Great article!",
  },
  {
    postId: 2,
    id: 18,
    name: "Robert Lewis",
    email: "robert.lewis@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 3,
    id: 19,
    name: "Thomas Johnson",
    email: "thomas.johnson@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 3,
    id: 20,
    name: "Jennifer Garcia",
    email: "jennifer.garcia@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 3,
    id: 21,
    name: "Elizabeth Thompson",
    email: "elizabeth.thompson@example.com",
    body: "Very informative post.",
  },
  {
    postId: 3,
    id: 22,
    name: "John Walker",
    email: "john.walker@example.com",
    body: "Helped me understand this better.",
  },
  {
    postId: 3,
    id: 23,
    name: "John Thomas",
    email: "john.thomas@example.com",
    body: "Awesome content!",
  },
  {
    postId: 3,
    id: 24,
    name: "Barbara Hall",
    email: "barbara.hall@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 4,
    id: 25,
    name: "Thomas Martin",
    email: "thomas.martin@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 4,
    id: 26,
    name: "Thomas Robinson",
    email: "thomas.robinson@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 4,
    id: 27,
    name: "Karen Garcia",
    email: "karen.garcia@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 4,
    id: 28,
    name: "Linda Martin",
    email: "linda.martin@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 4,
    id: 29,
    name: "Susan Lewis",
    email: "susan.lewis@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 4,
    id: 30,
    name: "Jessica Brown",
    email: "jessica.brown@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 4,
    id: 31,
    name: "Elizabeth Martinez",
    email: "elizabeth.martinez@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 4,
    id: 32,
    name: "Barbara Harris",
    email: "barbara.harris@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 5,
    id: 33,
    name: "William Walker",
    email: "william.walker@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 5,
    id: 34,
    name: "Jennifer Thomas",
    email: "jennifer.thomas@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 5,
    id: 35,
    name: "Charles Robinson",
    email: "charles.robinson@example.com",
    body: "Perfect explanation.",
  },
  {
    postId: 5,
    id: 36,
    name: "Patricia White",
    email: "patricia.white@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 5,
    id: 37,
    name: "Robert Brown",
    email: "robert.brown@example.com",
    body: "Very informative post.",
  },
  {
    postId: 5,
    id: 38,
    name: "Sarah Anderson",
    email: "sarah.anderson@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 5,
    id: 39,
    name: "Richard Lee",
    email: "richard.lee@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 5,
    id: 40,
    name: "John Jackson",
    email: "john.jackson@example.com",
    body: "Perfect explanation.",
  },
  {
    postId: 5,
    id: 41,
    name: "Jennifer Rodriguez",
    email: "jennifer.rodriguez@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 5,
    id: 42,
    name: "John Martin",
    email: "john.martin@example.com",
    body: "Awesome content!",
  },
  {
    postId: 6,
    id: 43,
    name: "William Walker",
    email: "william.walker@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 6,
    id: 44,
    name: "Jennifer Brown",
    email: "jennifer.brown@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 6,
    id: 45,
    name: "Sarah White",
    email: "sarah.white@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 6,
    id: 46,
    name: "Robert Martin",
    email: "robert.martin@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 6,
    id: 47,
    name: "Barbara Taylor",
    email: "barbara.taylor@example.com",
    body: "Perfect explanation.",
  },
  {
    postId: 6,
    id: 48,
    name: "Susan Lee",
    email: "susan.lee@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 6,
    id: 49,
    name: "Mary Martin",
    email: "mary.martin@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 6,
    id: 50,
    name: "Charles Martin",
    email: "charles.martin@example.com",
    body: "Exactly what I needed.",
  },
  {
    postId: 6,
    id: 51,
    name: "Joseph Martinez",
    email: "joseph.martinez@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 7,
    id: 52,
    name: "Michael Walker",
    email: "michael.walker@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 7,
    id: 53,
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 7,
    id: 54,
    name: "Elizabeth Thomas",
    email: "elizabeth.thomas@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 7,
    id: 55,
    name: "Elizabeth Thompson",
    email: "elizabeth.thompson@example.com",
    body: "Good explanation, thanks.",
  },
  {
    postId: 7,
    id: 56,
    name: "Jennifer Smith",
    email: "jennifer.smith@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 7,
    id: 57,
    name: "Thomas Taylor",
    email: "thomas.taylor@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 7,
    id: 58,
    name: "William Thompson",
    email: "william.thompson@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 7,
    id: 59,
    name: "Charles Clark",
    email: "charles.clark@example.com",
    body: "Helped me understand this better.",
  },
  {
    postId: 7,
    id: 60,
    name: "Jessica Harris",
    email: "jessica.harris@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 7,
    id: 61,
    name: "Jennifer Lewis",
    email: "jennifer.lewis@example.com",
    body: "Awesome content!",
  },
  {
    postId: 8,
    id: 62,
    name: "James Rodriguez",
    email: "james.rodriguez@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 8,
    id: 63,
    name: "Charles Martinez",
    email: "charles.martinez@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 8,
    id: 64,
    name: "Thomas Taylor",
    email: "thomas.taylor@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 8,
    id: 65,
    name: "Barbara Rodriguez",
    email: "barbara.rodriguez@example.com",
    body: "Great article!",
  },
  {
    postId: 8,
    id: 66,
    name: "Robert Walker",
    email: "robert.walker@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 8,
    id: 67,
    name: "Joseph Anderson",
    email: "joseph.anderson@example.com",
    body: "Wonderful post, thank you.",
  },
  {
    postId: 8,
    id: 68,
    name: "Richard Johnson",
    email: "richard.johnson@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 8,
    id: 69,
    name: "Sarah Martin",
    email: "sarah.martin@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 8,
    id: 70,
    name: "Karen Rodriguez",
    email: "karen.rodriguez@example.com",
    body: "Awesome content!",
  },
  {
    postId: 8,
    id: 71,
    name: "Barbara Robinson",
    email: "barbara.robinson@example.com",
    body: "Awesome content!",
  },
  {
    postId: 9,
    id: 72,
    name: "Robert Walker",
    email: "robert.walker@example.com",
    body: "Awesome content!",
  },
  {
    postId: 9,
    id: 73,
    name: "Charles Taylor",
    email: "charles.taylor@example.com",
    body: "Perfect explanation.",
  },
  {
    postId: 9,
    id: 74,
    name: "William Robinson",
    email: "william.robinson@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 9,
    id: 75,
    name: "Sarah Brown",
    email: "sarah.brown@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 9,
    id: 76,
    name: "Barbara Lee",
    email: "barbara.lee@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 9,
    id: 77,
    name: "James Clark",
    email: "james.clark@example.com",
    body: "Awesome content!",
  },
  {
    postId: 9,
    id: 78,
    name: "Richard Brown",
    email: "richard.brown@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 10,
    id: 79,
    name: "Michael Walker",
    email: "michael.walker@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 10,
    id: 80,
    name: "Susan Jackson",
    email: "susan.jackson@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 10,
    id: 81,
    name: "Charles Brown",
    email: "charles.brown@example.com",
    body: "Great article!",
  },
  {
    postId: 10,
    id: 82,
    name: "Jennifer Clark",
    email: "jennifer.clark@example.com",
    body: "Perfect explanation.",
  },
  {
    postId: 10,
    id: 83,
    name: "Jessica Hall",
    email: "jessica.hall@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 10,
    id: 84,
    name: "Linda Johnson",
    email: "linda.johnson@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 10,
    id: 85,
    name: "Susan Johnson",
    email: "susan.johnson@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 11,
    id: 86,
    name: "Elizabeth Garcia",
    email: "elizabeth.garcia@example.com",
    body: "Good explanation, thanks.",
  },
  {
    postId: 11,
    id: 87,
    name: "Richard Garcia",
    email: "richard.garcia@example.com",
    body: "Wonderful post, thank you.",
  },
  {
    postId: 11,
    id: 88,
    name: "Jennifer Robinson",
    email: "jennifer.robinson@example.com",
    body: "Exactly what I needed.",
  },
  {
    postId: 11,
    id: 89,
    name: "Richard White",
    email: "richard.white@example.com",
    body: "Good explanation, thanks.",
  },
  {
    postId: 11,
    id: 90,
    name: "Charles Lewis",
    email: "charles.lewis@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 11,
    id: 91,
    name: "David Lee",
    email: "david.lee@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 11,
    id: 92,
    name: "Sarah Smith",
    email: "sarah.smith@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 11,
    id: 93,
    name: "Joseph Harris",
    email: "joseph.harris@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 12,
    id: 94,
    name: "Richard Jackson",
    email: "richard.jackson@example.com",
    body: "Loved the insights here!",
  },
  {
    postId: 12,
    id: 95,
    name: "Sarah Lee",
    email: "sarah.lee@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 12,
    id: 96,
    name: "James Lee",
    email: "james.lee@example.com",
    body: "Loved the insights here!",
  },
  {
    postId: 12,
    id: 97,
    name: "Jessica Johnson",
    email: "jessica.johnson@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 12,
    id: 98,
    name: "Jessica Jackson",
    email: "jessica.jackson@example.com",
    body: "Awesome content!",
  },
  {
    postId: 12,
    id: 99,
    name: "Charles Anderson",
    email: "charles.anderson@example.com",
    body: "Very informative post.",
  },
  {
    postId: 12,
    id: 100,
    name: "Charles Garcia",
    email: "charles.garcia@example.com",
    body: "Good explanation, thanks.",
  },
  {
    postId: 12,
    id: 101,
    name: "Michael Anderson",
    email: "michael.anderson@example.com",
    body: "Loved the insights here!",
  },
  {
    postId: 12,
    id: 102,
    name: "Elizabeth Thomas",
    email: "elizabeth.thomas@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 12,
    id: 103,
    name: "Thomas Martinez",
    email: "thomas.martinez@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 13,
    id: 104,
    name: "Joseph Jackson",
    email: "joseph.jackson@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 13,
    id: 105,
    name: "Robert Thomas",
    email: "robert.thomas@example.com",
    body: "Awesome content!",
  },
  {
    postId: 13,
    id: 106,
    name: "John Johnson",
    email: "john.johnson@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 13,
    id: 107,
    name: "Susan Clark",
    email: "susan.clark@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 13,
    id: 108,
    name: "Mary Brown",
    email: "mary.brown@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 13,
    id: 109,
    name: "James Lewis",
    email: "james.lewis@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 13,
    id: 110,
    name: "Patricia Robinson",
    email: "patricia.robinson@example.com",
    body: "Wonderful post, thank you.",
  },
  {
    postId: 13,
    id: 111,
    name: "Charles Robinson",
    email: "charles.robinson@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 13,
    id: 112,
    name: "Patricia White",
    email: "patricia.white@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 14,
    id: 113,
    name: "Jennifer Martin",
    email: "jennifer.martin@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 14,
    id: 114,
    name: "Jessica Rodriguez",
    email: "jessica.rodriguez@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 14,
    id: 115,
    name: "Susan Walker",
    email: "susan.walker@example.com",
    body: "Awesome content!",
  },
  {
    postId: 14,
    id: 116,
    name: "James Jackson",
    email: "james.jackson@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 14,
    id: 117,
    name: "Joseph Anderson",
    email: "joseph.anderson@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 14,
    id: 118,
    name: "James Walker",
    email: "james.walker@example.com",
    body: "Helped me understand this better.",
  },
  {
    postId: 15,
    id: 119,
    name: "Jennifer Johnson",
    email: "jennifer.johnson@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 15,
    id: 120,
    name: "Thomas Anderson",
    email: "thomas.anderson@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 15,
    id: 121,
    name: "Charles Thompson",
    email: "charles.thompson@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 15,
    id: 122,
    name: "Robert Hall",
    email: "robert.hall@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 15,
    id: 123,
    name: "John Anderson",
    email: "john.anderson@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 15,
    id: 124,
    name: "William Johnson",
    email: "william.johnson@example.com",
    body: "Good explanation, thanks.",
  },
  {
    postId: 15,
    id: 125,
    name: "Robert Jackson",
    email: "robert.jackson@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 15,
    id: 126,
    name: "Jessica Smith",
    email: "jessica.smith@example.com",
    body: "Awesome content!",
  },
  {
    postId: 15,
    id: 127,
    name: "Robert Harris",
    email: "robert.harris@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 15,
    id: 128,
    name: "Susan Jackson",
    email: "susan.jackson@example.com",
    body: "Perfect explanation.",
  },
  {
    postId: 16,
    id: 129,
    name: "Linda Hall",
    email: "linda.hall@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 16,
    id: 130,
    name: "David Lewis",
    email: "david.lewis@example.com",
    body: "Good explanation, thanks.",
  },
  {
    postId: 16,
    id: 131,
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    body: "Awesome content!",
  },
  {
    postId: 16,
    id: 132,
    name: "Jessica Harris",
    email: "jessica.harris@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 16,
    id: 133,
    name: "Linda Robinson",
    email: "linda.robinson@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 16,
    id: 134,
    name: "John Anderson",
    email: "john.anderson@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 16,
    id: 135,
    name: "Michael Robinson",
    email: "michael.robinson@example.com",
    body: "Great article!",
  },
  {
    postId: 17,
    id: 136,
    name: "James Martin",
    email: "james.martin@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 17,
    id: 137,
    name: "Jessica Martin",
    email: "jessica.martin@example.com",
    body: "Very informative post.",
  },
  {
    postId: 17,
    id: 138,
    name: "Richard Anderson",
    email: "richard.anderson@example.com",
    body: "Well said and structured.",
  },
  {
    postId: 17,
    id: 139,
    name: "Thomas Rodriguez",
    email: "thomas.rodriguez@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 17,
    id: 140,
    name: "Jennifer Rodriguez",
    email: "jennifer.rodriguez@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 17,
    id: 141,
    name: "Mary Clark",
    email: "mary.clark@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 17,
    id: 142,
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 18,
    id: 143,
    name: "James Taylor",
    email: "james.taylor@example.com",
    body: "Loved the insights here!",
  },
  {
    postId: 18,
    id: 144,
    name: "David Walker",
    email: "david.walker@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 18,
    id: 145,
    name: "Joseph Jackson",
    email: "joseph.jackson@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 18,
    id: 146,
    name: "David Thompson",
    email: "david.thompson@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 18,
    id: 147,
    name: "Charles Anderson",
    email: "charles.anderson@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 18,
    id: 148,
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    body: "Loved the insights here!",
  },
  {
    postId: 18,
    id: 149,
    name: "Susan Lewis",
    email: "susan.lewis@example.com",
    body: "Helped me understand this better.",
  },
  {
    postId: 19,
    id: 150,
    name: "Joseph Lee",
    email: "joseph.lee@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 19,
    id: 151,
    name: "Michael Garcia",
    email: "michael.garcia@example.com",
    body: "Helped me understand this better.",
  },
  {
    postId: 19,
    id: 152,
    name: "Richard Robinson",
    email: "richard.robinson@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 19,
    id: 153,
    name: "Patricia Hall",
    email: "patricia.hall@example.com",
    body: "Exactly what I needed.",
  },
  {
    postId: 19,
    id: 154,
    name: "Joseph Brown",
    email: "joseph.brown@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 19,
    id: 155,
    name: "David Hall",
    email: "david.hall@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 20,
    id: 156,
    name: "Patricia Robinson",
    email: "patricia.robinson@example.com",
    body: "Great article!",
  },
  {
    postId: 20,
    id: 157,
    name: "David Taylor",
    email: "david.taylor@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 20,
    id: 158,
    name: "Karen Brown",
    email: "karen.brown@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 20,
    id: 159,
    name: "James Anderson",
    email: "james.anderson@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 20,
    id: 160,
    name: "Jessica Walker",
    email: "jessica.walker@example.com",
    body: "Loved the insights here!",
  },
  {
    postId: 20,
    id: 161,
    name: "David Clark",
    email: "david.clark@example.com",
    body: "Exactly what I needed.",
  },
  {
    postId: 20,
    id: 162,
    name: "Robert Smith",
    email: "robert.smith@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 21,
    id: 163,
    name: "William Walker",
    email: "william.walker@example.com",
    body: "Loved the insights here!",
  },
  {
    postId: 21,
    id: 164,
    name: "Sarah Jackson",
    email: "sarah.jackson@example.com",
    body: "Useful from start to finish.",
  },
  {
    postId: 21,
    id: 165,
    name: "William White",
    email: "william.white@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 21,
    id: 166,
    name: "Patricia Robinson",
    email: "patricia.robinson@example.com",
    body: "Super easy to follow.",
  },
  {
    postId: 21,
    id: 167,
    name: "Richard Smith",
    email: "richard.smith@example.com",
    body: "Exactly what I needed.",
  },
  {
    postId: 21,
    id: 168,
    name: "Susan Smith",
    email: "susan.smith@example.com",
    body: "Exactly what I needed.",
  },
  {
    postId: 22,
    id: 169,
    name: "Mary Jackson",
    email: "mary.jackson@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 22,
    id: 170,
    name: "Jessica Lee",
    email: "jessica.lee@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 22,
    id: 171,
    name: "William Lee",
    email: "william.lee@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 22,
    id: 172,
    name: "Barbara Hall",
    email: "barbara.hall@example.com",
    body: "Much appreciated!",
  },
  {
    postId: 22,
    id: 173,
    name: "Barbara Martin",
    email: "barbara.martin@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 22,
    id: 174,
    name: "Richard Martin",
    email: "richard.martin@example.com",
    body: "Exactly what I needed.",
  },
  {
    postId: 23,
    id: 175,
    name: "Mary Martinez",
    email: "mary.martinez@example.com",
    body: "Nicely put together.",
  },
  {
    postId: 23,
    id: 176,
    name: "John Clark",
    email: "john.clark@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 23,
    id: 177,
    name: "Karen Harris",
    email: "karen.harris@example.com",
    body: "Helped me understand this better.",
  },
  {
    postId: 23,
    id: 178,
    name: "Mary Martin",
    email: "mary.martin@example.com",
    body: "Loved the insights here!",
  },
  {
    postId: 23,
    id: 179,
    name: "Sarah Martin",
    email: "sarah.martin@example.com",
    body: "Thanks for the helpful info!",
  },
  {
    postId: 23,
    id: 180,
    name: "Charles Martin",
    email: "charles.martin@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 23,
    id: 181,
    name: "Linda Thomas",
    email: "linda.thomas@example.com",
    body: "Awesome content!",
  },
  {
    postId: 24,
    id: 182,
    name: "James Jackson",
    email: "james.jackson@example.com",
    body: "Great breakdown of the topic.",
  },
  {
    postId: 24,
    id: 183,
    name: "Susan Lewis",
    email: "susan.lewis@example.com",
    body: "Awesome content!",
  },
  {
    postId: 24,
    id: 184,
    name: "John Rodriguez",
    email: "john.rodriguez@example.com",
    body: "Good explanation, thanks.",
  },
  {
    postId: 24,
    id: 185,
    name: "Sarah Lewis",
    email: "sarah.lewis@example.com",
    body: "Concise and well-written.",
  },
  {
    postId: 24,
    id: 186,
    name: "Patricia Harris",
    email: "patricia.harris@example.com",
    body: "Helped me understand this better.",
  },
  {
    postId: 24,
    id: 187,
    name: "Barbara White",
    email: "barbara.white@example.com",
    body: "I found this very helpful.",
  },
  {
    postId: 24,
    id: 188,
    name: "Joseph Robinson",
    email: "joseph.robinson@example.com",
    body: "Very informative post.",
  },
  {
    postId: 25,
    id: 189,
    name: "David Brown",
    email: "david.brown@example.com",
    body: "Helped me understand this better.",
  },
  {
    postId: 25,
    id: 190,
    name: "Richard Lewis",
    email: "richard.lewis@example.com",
    body: "Awesome content!",
  },
  {
    postId: 25,
    id: 191,
    name: "Jessica Anderson",
    email: "jessica.anderson@example.com",
    body: "This really helped me out.",
  },
  {
    postId: 25,
    id: 192,
    name: "Sarah Robinson",
    email: "sarah.robinson@example.com",
    body: "Appreciate the clarity.",
  },
  {
    postId: 25,
    id: 193,
    name: "Charles Brown",
    email: "charles.brown@example.com",
    body: "Very informative post.",
  },
  {
    postId: 25,
    id: 194,
    name: "John Rodriguez",
    email: "john.rodriguez@example.com",
    body: "Much appreciated!",
  },
];

export default function handler(req, res) {
  // === CORS HEADERS ===
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET, POST, PUT, DELETE, OPTIONS"
  );
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }
  // ======================

  const { method, url } = req;
  const match = url.match(/\/api\/comments\/?(\d+)?/);
  const id = match?.[1] ? parseInt(match[1]) : null;

  if (method === "GET") {
    if (id) {
      const comment = comments.find((c) => c.id === id);
      if (!comment) {
        return res.status(404).json({ message: "Comment not found" });
      }
      res.setHeader("Content-Type", "application/json");
      return res.status(200).send(JSON.stringify(comment, null, 2));
    }
    res.setHeader("Content-Type", "application/json");
    return res.status(200).send(JSON.stringify(comments, null, 2));
  }

  if (method === "POST") {
    const newComment = req.body;
    newComment.id = comments.length
      ? Math.max(...comments.map((c) => c.id)) + 1
      : 1;
    comments.push(newComment);
    return res.status(201).json(newComment);
  }

  if (method === "PUT") {
    if (!id) return res.status(400).json({ message: "Missing comment ID" });
    const index = comments.findIndex((c) => c.id === id);
    if (index === -1)
      return res.status(404).json({ message: "Comment not found" });
    comments[index] = { ...comments[index], ...req.body };
    return res.status(200).json(comments[index]);
  }

  if (method === "DELETE") {
    if (!id) return res.status(400).json({ message: "Missing comment ID" });
    const index = comments.findIndex((c) => c.id === id);
    if (index === -1)
      return res.status(404).json({ message: "Comment not found" });
    comments.splice(index, 1);
    return res.status(204).end();
  }

  return res.status(405).json({ message: "Method not allowed" });
}
